services:
  hex-backend-alpha:
    build:
      context: ../  # 指向项目根目录
      dockerfile: Dockerfile
    image: hex-backend-alpha:latest
    container_name: hex-backend
    ports:
      - "541:8080"
    networks:
      - hex-network-alpha
    restart: always


networks:
  hex-network-alpha:
    driver: bridge
