services:
  hex-backend:
    build:
      context: ../  # 指向项目根目录
      dockerfile: Dockerfile
    image: hex-backend:latest
    container_name: hex-backend
    ports:
      - "541:8080"
    networks:
      - hex-network
    restart: always


networks:
  hex-network:
    driver: bridge
